
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_schema?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: secretKey = "secret-s--ssss-s-p-d--c-b--g--f--dsakey